name: arp_vendor_lookup
description: "Client app for looking up ARP vendor information."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
  flutter: 3.44.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
